### Get all groups with default pagination
GET http://localhost:8030/group?page=0&size=10
Accept: application/json

### Get all groups with custom page size
GET http://localhost:8030/group?page=0&size=20
Accept: application/json

### Get all groups sorted by name ascending
GET http://localhost:8030/group?sort=name&direction=asc&page=0&size=10
Accept: application/json

### Get all groups sorted by name descending
GET http://localhost:8030/group?sort=name&direction=desc&page=0&size=10
Accept: application/json

### Get second page of groups
GET http://localhost:8030/group?page=1&size=10
Accept: application/json

###
