services:
  postgres:
    image: postgres:15
    container_name: rafiq-db
    environment:
      POSTGRES_DB: rafiq
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5460:5432"
    restart: always

  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "8888:8080"
    depends_on:
      - postgres
    restart: always
  mail-dev:
    image: maildev/maildev:latest
    container_name: mail-dev
    ports:
      - "3080:3080"
      - "1025:1025"
    command: [ "--web", "3080", "--smtp", "1025", "--web-ip", "0.0.0.0" ]
    restart: unless-stopped


