
services:
  postgres:
    image: postgres:15
    container_name: rafiq-db
    environment:
      POSTGRES_DB: rafiq
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5460:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    networks:
      - rafiq-network

  spring:
    image: myapp:latest
    container_name: rafiq-api
    ports:
      - "8030:8030"
    depends_on:
      - postgres
      - mail-dev
    environment:
      # Database config
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/rafiq
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      # Mail config (use MailDev)
      MAIL_HOST: mail-dev
      MAIL_PORT: 1025
      MAIL_USERNAME: bialy
      MAIL_PASSWORD: bialy
      MAIL_PROTOCOL: smtp
      MAIL_SMTP_AUTH: "true"
      MAIL_SMTP_STARTTLS_ENABLE: "true"
      MAIL_SMTP_STARTTLS_REQUIRE: "true"
      MAIL_SMTP_CONNECTION_TIMEOUT: 5000
      MAIL_SMTP_TIMEOUT: 3000
      MAIL_SMTP_WRITE_TIMEOUT: 5000
      MAIL_SMTP_TRUST: "*"
      # JWT config
      JWT_SECRET: 6f8e8219c9147e4fd69b1ca054a33f981f3464c79cc3d8688ed93e9c87fd2e56
      JWT_EXPIRATION: 3600000
      # Refresh token config
      REFRESH_EXPIRATION: 600000000
      # OTP config
      OTP_EXPIRATION: 300000
      # Access token config
      ACCESS_TOKEN_EXPIRATION: 360000
      #OAuth2 Google
      GOOGLE_CLIENT_ID: 674352979461-s3eeqrfte3254663qm4i1oq5alhbmb80.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET: 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
      # OAuth2 Facebook
      FACEBOOK_CLIENT_ID: 24714780961515318
      FACEBOOK_CLIENT_SECRET: b63d0d699f88da369eca0542f72ceb5a
      # Cloudinary
      CLOUDINARY_CLOUD_NAME: dbdkrenhl
      CLOUDINARY_API_KEY: 974593956567557
      CLOUDINARY_API_SECRET: 3PAziKNw52iCHEaFMia0iOVMz-4
      # Google GenAI Config
      GOOGLE_GENAI_API_KEY: AIzaSyCb6fcMHBwrOXhXFHt8mLyMUQtbHfQ7kp4
      GOOGLE_GENAI_MODEL: gemini-2.5-pro



    networks:
      - rafiq-network
    restart: always

  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "8888:8080"
    depends_on:
      - postgres
    restart: always
    networks:
      - rafiq-network

  mail-dev:
    image: maildev/maildev:latest
    container_name: mail-dev
    ports:
      - "3080:3080"  # Web UI (http://localhost:3080)
      - "1025:1025"  # SMTP server
    command: [ "--web", "3080", "--smtp", "1025", "--web-ip", "0.0.0.0" ]
    restart: unless-stopped
    networks:
      - rafiq-network

networks:
  rafiq-network:

volumes:
  postgres-data:
    name: rafiq-postgres-data
