spring:
  # Database Config
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  # JPA Config
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true
      format_sql: true
  # File Upload Config
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 40MB
  # OAuth2 Config
  security:
    oauth2:
      client:
        registration:
  # Google OAuth2 Config
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
  # Facebook OAuth2 Config
          facebook:
            clientId: ${FACEBOOK_CLIENT_ID}
            clientSecret: ${FACEBOOK_CLIENT_SECRET}
# Mail Config
  mail:
   host: ${MAIL_HOST}
   port: ${MAIL_PORT}
   username: ${MAIL_USERNAME}
   password: ${MAIL_PASSWORD}
   protocol: ${MAIL_PROTOCOL}
   properties:
     mail:
       smtp:
         auth: ${MAIL_SMTP_AUTH}
         starttls:
           enable: ${MAIL_SMTP_STARTTLS_ENABLE}
           required: ${MAIL_SMTP_STARTTLS_REQUIRE}
         connectiontimeout: ${MAIL_SMTP_CONNECTION_TIMEOUT}
         timeout: ${MAIL_SMTP_TIMEOUT}
         writetimeout: ${MAIL_SMTP_WRITE_TIMEOUT}
         trust: ${MAIL_SMTP_TRUST}
# AI Config
  ai:
    google:
      genai:
        api-key: ${GOOGLE_GENAI_API_KEY}
# Cloudinary Config
cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}
# JWT Config
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
# refresh token expiration
refresh:
  expiration: ${REFRESH_EXPIRATION}
# otp expiration
otp:
  expiration: ${OTP_EXPIRATION}
# access token expiration
access:
  token:
    expiration: ${ACCESS_TOKEN_EXPIRATION}
# server port
server:
  port: ${SERVER_PORT}



