spring.application.name=rafiq

## database configuration
spring.datasource.url=jdbc:postgresql://localhost:5460/rafiq
spring.datasource.username=postgres
spring.datasource.password=root


## jpa configuration
## we should use flyway for migration instead of this
spring.jpa.hibernate.ddl-auto=update
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.show_sql=true
hibernate.format_sql=true


server.port=8032


logging.pattern.console=${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
logging.level.org.springframework.security=${SPRING_SECURITY_LOG_LEVEL:TRACE}

