spring.application.name=rafiq

### database configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5460/rafiq}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driver-class-name=org.postgresql.Driver
# Database connection remote
#spring.datasource.url=jdbc:postgresql://aws-1-eu-north-1.pooler.supabase.com:5432/postgres?sslmode=require
#spring.datasource.username=postgres.jjvtpktumyydmgonejyg
#spring.datasource.password=JjX@$VCLHEYLhj5

## jpa configuration
## we should use flyway for migration instead of this
spring.jpa.hibernate.ddl-auto=create-drop
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.show_sql=true
hibernate.format_sql=true
spring.servlet.multipart.max-request-size=150MB
spring.servlet.multipart.max-file-size=1000MB


server.port=8030
server.address=0.0.0.0




## todo change this to .env file
spring.security.user.name=${SECURITY_USERNAME:fighter}
spring.security.user.password=${SECURITY_PASSWORD:root}

## OAUTH2 configuration
## google configuration
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:674352979461-s3eeqrfte3254663qm4i1oq5alhbmb80.apps.googleusercontent.com}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET: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}
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.redirect-uri=${GOOGLE_REDIRECT_URI:http://localhost:8032/login/oauth2/code/google}

## facebook configuration
spring.security.oauth2.client.registration.facebook.client-id=${FACEBOOK_CLIENT_ID:24714780961515318}
spring.security.oauth2.client.registration.facebook.client-secret=${FACEBOOK_CLIENT_SECRET:b63d0d699f88da369eca0542f72ceb5a}
# JWT configuration
jwt.secret=${JWT_SECRET:6f8e8219c9147e4fd69b1ca054a33f981f3464c79cc3d8688ed93e9c87fd2e56}
jwt.expiration=${JWT_EXPIRATION:3600000}
# Refresh token configuration
refresh.expiration=${REFRESH_EXPIRATION:3600000000}
# OTP configuration
otp.expiration=${OTP_EXPIRATION:300000}
#Access token expiration
access.token.expiration=${ACCESS_TOKEN_EXPIRATION:360000}
#Mail configuration
spring.mail.host=${MAIL_HOST:localhost}
spring.mail.port=${MAIL_PORT:1025}
spring.mail.username=${MAIL_USERNAME:bialy}
spring.mail.password=${MAIL_PASSWORD:bialy}
spring.mail.protocol=${MAIL_PROTOCOL:smtp}

spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_SMTP_STARTTLS_ENABLE:true}
spring.mail.properties.mail.smtp.starttls.require=${MAIL_SMTP_STARTTLS_REQUIRE:true}
spring.mail.properties.mail.smtp.connectiontimeout=${MAIL_SMTP_CONNECTION_TIMEOUT:5000}
spring.mail.properties.mail.smtp.timeout=${MAIL_SMTP_TIMEOUT:3000}
spring.mail.properties.mail.smtp.writetimeout=${MAIL_SMTP_WRITE_TIMEOUT:5000}
spring.mail.properties.mail.smtp.trust=${MAIL_SMTP_TRUST:*}

# cloudinary configuration
cloudinary.cloud-name=dbdkrenhl
cloudinary.api-key=974593956567557
cloudinary.api-secret=3PAziKNw52iCHEaFMia0iOVMz-4

# Tesseract OCR configuration
tesseract.datapath=${TESSERACT_DATAPATH:/usr/share/tesseract-ocr/5/}
tesseract.language=${TESSERACT_LANGUAGE:eng}
#Gemini configuration
spring.ai.google.genai.api-key=AIzaSyCb6fcMHBwrOXhXFHt8mLyMUQtbHfQ7kp4
google.ai.google.genai.chat.options.model=gemini-2.5-pro

