### Change password using a valid access token (204 No Content)
POST http://localhost:8030/auth/change-password
Content-Type: application/json
Accept: application/json

{
  "accessToken": "<paste_access_token_here>",
  "newPassword": "Str0ng@Pass1!"
}

###
