### Login with email and password (returns LoginResponse)
POST http://localhost:8030/auth/login
Content-Type: application/json
Accept: application/json

{
  "email": "oke@example.com",
  "password": "Str0ng@Pass1!"
}

###
