### Verify user email (returns LoginResponse)
POST http://localhost:8030/user/verification
Content-Type: application/json
Accept: application/json

{
  "email": "john.doe@example.com",
  "otp": "225122"
}

###
