### Verify user email (returns LoginResponse)
POST http://localhost:8030/user/verification
Content-Type: application/json
Accept: application/json

{
  "email": "oke@example.com",
  "otp": "941171"
}

###
