### Get all reminders with default pagination
GET http://localhost:8030/reminder/all
Accept: application/json

###

### Get all reminders with pagination (page 0, size 10)
GET http://localhost:8030/reminder/all?page=0&size=10
Accept: application/json

###

### Get all reminders (page 1, size 20)
GET http://localhost:8030/reminder/all?page=1&size=20
Accept: application/json

###

### Get all reminders sorted by time ascending
GET http://localhost:8030/reminder/all?page=0&size=15&sort=time,asc
Accept: application/json

###

### Get all reminders sorted by time descending
GET http://localhost:8030/reminder/all?page=0&size=15&sort=time,desc
Accept: application/json

###
