### Update Reminder Vibration - Enable
PATCH http://localhost:8030/reminder/updateVibration/true/reminder/{{reminder-id}}
Authorization: Bearer {{access_token}}

###

### Update Reminder Vibration - Disable
PATCH http://localhost:8030/reminder/updateVibration/false/reminder/{{reminder-id}}
Authorization: Bearer {{access_token}}

