package com.nexaworks.rafiq.entities.enums;

public enum ActionStatus {
    CONSULTATION_CANCELLED, CONSULTATION_COMING_UP, CONSULTATION_DONE, CONSULTATION_EXPIRED, REFUND_SUCCESS, REFUND_FAILED, NEW_CONSULTATION, CONSULTATION_FAILED
}
