package com.nexaworks.rafiq.entities.enums;

public enum Specialization {
    // Internal Medicine
    INTERNAL_MEDICINE, CARDIOLOGY, ENDOCRINOLOGY, GASTROENTEROLOGY, HEMATOLOGY, INFECTIOUS_DISEASE, NEPHROLOGY, ONCOLOGY, PULMONOLOGY, RHEUMATOLOGY,

    // Surgery
    GENERAL_SURGERY, CARDIAC_SURGERY, COLORECTAL_SURGERY, NEUROSURGERY, ORTHOPEDIC_SURGERY, PLASTIC_SURGERY, THORACIC_SURGERY, TRANSPLANT_SURGERY, VASCULAR_SURGERY, UROLOGICAL_SURGERY,

    // Head & Neck
    OPHTHALMOLOGY, OTOLARYNGOLOGY, DENTISTRY, ORAL_MAXILLOFACIAL_SURGERY,

    // Nervous System
    NEUROLOGY, PSYCHIATRY, PSYCHOLOGY,

    // Women & Children
    OBSTETRICS, GYNECOLOGY, OBSTETRICS_GYNECOLOGY, PEDIATRICS, PEDIATRIC_SURGERY, NEONATOLOGY, REPRODUCTIVE_MEDICINE,

    // Skin & Musculoskeletal
    DERMATOLOGY, ORTHOPEDICS, RHEUMATOLOGY_IMMUNOLOGY,

    // Imaging & Diagnostics
    RADIOLOGY, NUCLEAR_MEDICINE, PATHOLOGY, CLINICAL_LABORATORY,

    // Emergency & Critical Care
    EMERGENCY_MEDICINE, CRITICAL_CARE, ANESTHESIOLOGY, PAIN_MANAGEMENT,

    // Other Specializations
    FAMILY_MEDICINE, GENERAL_PRACTICE, GERIATRICS, IMMUNOLOGY, ALLERGY, OCCUPATIONAL_MEDICINE, SPORTS_MEDICINE, PALLIATIVE_CARE, PHYSICAL_MEDICINE, REHABILITATION, VENEREOLOGY, TROPICAL_MEDICINE, AVIATION_MEDICINE, FORENSIC_MEDICINE
}
